### ISSUE TITLE
Proxying of live-reload traffic

### ISSUE THREAD

**Issue by sandstrom** [isleofcode/corber#253]
In our development setup we need to proxy the web sockets traffic. Because of this we have two ports:

1. The live-reload web sockets port listened to by ember-cordova
2. The live-reload web sockets port that the client connects to, which in turn is proxied to {1}.

Would you be open to adding a proxy option for this?

**Comment by alexblom** [comment]
Yes - there was actually a discussion in e-cordova around that. My roadmap over the last month has been focused on fixing install process + plugins, but I'm very open to helping with somebody on a PR :) I'll leave this open as it is definitely an issue.
