### ISSUE TITLE
add new documentation

### ISSUE THREAD

**Issue by jamesdixon** [isleofcode/corber#256]
This is just an issue to keep track of new documentation to be added based on conversations in the #e-cordova slack channel. Feel free to make suggestions:

- [ ] add cookbook page for recipes to common situations/problems
- [ ] add recommended add-ons list (plugins known to work well with e-cordova)

**Comment by alexblom** [comment]
- [ ] add contribution suggestions & dev roadmap

**Comment by alexblom** [comment]
I'm going to close this given the revamp of content at corber.io, and I think the added workflow solves some of the cookbook issues.

Please re-open if you think added/new docs would be useful.
