### ISSUE TITLE
Fastboot Compatibility

### ISSUE THREAD

**Issue by alexmasita** [isleofcode/corber#360]
Is this addon fastboot compatible?  Please let me know.

**Comment by alexblom** [comment]
I've not tried - what advantage would you be shooting for?

It is normal in this context to have packaged your JS inside the application container, so you are not dealing with the asset download time/issues fastboot aims to solve.

**Comment by alexmasita** [comment]
Hi Alexblom.  Thanks for your reply.

I think I understand you.  You mean to say that fastboot in the mobile context would be irrelevant because the assets are part of the mobile installation (assets already on the mobile client) but what about if you opted to still have the web version usable on the desktop without packaging it in a mobile native wrapper?  Wouldn't fastboot be relevant in that context?

**Comment by alexblom** [comment]
Hey Alex,

That's correct. I've not used fastboot in some time - is it possible to have an env under which it is disabled?

Your best bet may to have something along the lines of
```
config/environment.js

env.mobile {
  fastboot_disabled: true
}
```

You would then `ember cdv:b --env=mobile`.

I'm curious if we could detect fastboot and warn the user things will not work as they expect - seems like a good idea.
