### ISSUE TITLE
The name is not corgi.

### ISSUE THREAD

**Issue by runspired** [isleofcode/corber#365]
It's close, but it's obviously not Corgi.  Pugism is real.

**Comment by alexblom** [comment]
![image](https://user-images.githubusercontent.com/246898/29639656-80400248-8829-11e7-8b30-66f9ca1e8d4d.png)

**Comment by alexblom** [comment]
![image](https://user-images.githubusercontent.com/246898/29639676-8fbc9f42-8829-11e7-9185-5290025b348a.png)

**Comment by alexblom** [comment]
tbh it sounds much more like a helpful lab, so closing this issue

**Comment by jordanyee** [comment]
Yo. Sheesh.
