### ISSUE TITLE
plugins missing when using livereload

### ISSUE THREAD

**Issue by kbullaughey** [isleofcode/corber#373]
I added the plugin `cordova-plugin-device` and when I run:

    corber build

And then launch the app on my device from inside xcode I can see the `window.device` property and the associated plugin source files (like `device.js`) in the debugger.

But if I run:

    corber serve

Then I neither see the source file in the debugger or the `window.device` property.

If this is intentional then developing and testing any functionality requiring the plugins is going to be a big pain because live-reload makes the dev cycle wondrously fast. Thoughts?

**Comment by alexblom** [comment]
Thanks for the report - this is definitely a deficiency I am working on this week.

I'm only going to close this issue as I have it covered in #369. Expect Ember fixes to land in the next few days.

**Comment by alexblom** [comment]
It will likely be released with further improvements tomorrow, but Ember-only fixes can now be access from master. The merged PR can be found here: https://github.com/isleofcode/corber/pull/374
