### ISSUE TITLE
LiveReload Won't Work?

### ISSUE THREAD

**Issue by OakBehringer** [isleofcode/corber#396]
Whatup. Love this project. Been trying for hours to get livereload to work. Can't. 

corber@1.1.5 

I created a blank ember project. Nothing but two routes and a couple `{{link-to}}` to navigate between them. Works fine in browser, works fine in xcode emulator after running `corber build && corber open`. 

Exciting! My first time seeing a JS in the iPhone emulator. 

Now I want to get livereload working. Fire up a new terminal tab. Run `corber serve` - I see `corber: Device LiveReload is enabled` - yay!

New terminal tab, run `corber build` - I see warning about allow-navigation. LAN IP is correct. 

Run in emulator, no live reload. 
Run in laptop browser using localhost:4200, livereload works fine. 
Run in laptop browser using LAN-IP-ADDRESS:4200, livereload works fine. 
Run in iOS Safari browser using LAN-IP-ADDRESS:4200, livereload works fine. 

**Note: browser console shows "Could not find cordova.js script tag. Plugin loading may fail."**

Any suggestions, tips, tricks to get this working? 

Thanks!
Adam

**Comment by OakBehringer** [comment]
Might be worth noting: Looking at corber/cordova/www/index.html, I **DO** see `<script src="cordova.js"></script>` immediately after the opening body tag. 

Might be worth noting: Looking at corber/tmp-live-reload/index.html, I **DO NOT** see `<script src="cordova.js"></script>` immediately after the opening body tag. 

Both directories are present, while corber serve is running. 

Thanks!
Adam

**Comment by machty** [comment]
I believe I'm seeing the same symptoms (no script tag in tmp-live-reload).

I don't know if this is related by seems like `treeFor()` is never getting called when i do `corber s` (even though all the code around it is getting called): https://github.com/isleofcode/corber/blob/master/lib/frameworks/ember/tasks/serve.js#L38

**Comment by alexblom** [comment]
Thanks for the report, this is definitely why you are seeing problems. My test projects have that treeFor firing. Can you confirm what version of ember you are building with, so I can init the same env?

**Comment by OakBehringer** [comment]
```
ember-cli: 2.16.2

 "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "corber": "1.1.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~2.16.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-data": "~2.16.2",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.16.0",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },

```
I'm just as surprised as you are, that I'm totally up to date.

**Comment by alexblom** [comment]
With the same env I'm having trouble replicating. Are you on the ember-slack at all where we can do a quick screenshare?

**Comment by OakBehringer** [comment]
High tech professional debugging:

![image](https://user-images.githubusercontent.com/2909414/32121120-151a2844-bb10-11e7-9353-551e69dd4609.png)

run `corber serve`...

```
** BUILD SUCCEEDED **

tree for deez nutz
tree for deez nutz
tree for deez nutz
tree for deez nutz
tree for deez nutz
tree for deez nutz
tree for deez nutz
tree for deez nutz
Livereload server on http://localhost:8000

Build successful (16804ms)
```
treeFor is being called

**Comment by alexblom** [comment]
Thanks! I'm a little unclear if this means the issue has resolved for you, or if we've just ruled out treeFor as the problem?

**Comment by OakBehringer** [comment]
@alexblom Just saw that reply... I have to leave right now for a few hours. I'll try to get on the slack channel later today, but I can't make any promises, I have the day off :)

Oh - it's still a problem - I have no idea what treeFor is doing, which that other guy referenced, just wanted to let you know that it IS being called.

**Comment by alexblom** [comment]
Thanks. I'm @alexblom on ember-slack as well.

A small note from re-reading your issue, after running `corber s` you do not need to run `corber b` - you simply want to flash to your device (with xcode/android studio, or the `cordova run --nobuild` command).

Running `corber b` afterwards will actually replace the livereload shell. The app should still work, but you won't get any livereload from that.

**Comment by OakBehringer** [comment]
Ahhhhh... don't `build` after `serve`. That did it! Live reload is working. The following line in your documentation is what threw me off:

![image](https://user-images.githubusercontent.com/2909414/32136250-42c9ea40-bbbf-11e7-8710-ccd4fa67db5a.png)

It kinda reads like the build steps should be taken. Makes sense in hindsight. 

Regardless, it's working now. Awesome project, thank you for your help.

**Comment by alexblom** [comment]
Thanks for the heads up. I'll rewrite those parts of the docs to be clearer.
