### ISSUE TITLE
splashscreenService: service('corber/splash') throws an error.

### ISSUE THREAD

**Issue by alexmasita** [isleofcode/corber#402]
I am receiving the following error: Assertion Failed: Attempting to inject an unknown injection: 'service:corber/splash'.

Could it be because corber is no longer packaged as an addon and now does not merge in the service?

**Comment by alexblom** [comment]
I think you are looking for ember-cordova/splash. Do we have it named as corber/splash anywhere?

As an aside, I'm debating the names of these ember-only services. Should we remain as ember-cordova/splash, or something along the lines of corber-ember/splash?

**Comment by alexmasita** [comment]
Thanks for your reply.  Actually yes, on the corber page here: [Corber Website](http://corber.io/pages/workflow/icon_splash_management) where there is code for injecting the splash service.  You might need to update that.

As for the naming, I kind of like the simplicity of corber/splash and I take it that if they are ember-only, then there is no motivation for differentiating?  My two cents :).

**Comment by alexblom** [comment]
Thanks, have fixed the docs. Yep - those addons are ember only :)

**Comment by evoactivity** [comment]
Do I need to install ember-cordova as well as corber for this? I want my app to run in the browser as well so I'm getting `Attempting to inject an unknown injection: 'service:ember-cordova/splash'` in my console.
