### ISSUE TITLE
Could not find module ember-resolver

### ISSUE THREAD

**Issue by pythonquick** [isleofcode/corber#409]
Today i switched from ember-cordova to corber.

On the iPhone i get a white blank screen. After putting some manual statements into the assets/myapplication.js file, i found that the following section fails:

```
if (!runningTests) {
  require("myapplication/app")["default"].create({"name":"myapplication","version":"0.0.0+108fc194"});
}
```

There's an exception when it runs the `require` function:

```
Could not find module `ember-resolver` imported from `myapplication/resolver`
```

It seems the vendor.js file is much smaller in the corber/cordova/www/assets directory vs the dist/assets directory
* corber/cordova/www/assets/vendor.js is 2.7 MB
* dist/assets/vendor.js is 4.1 MB
(in non-minified debug configuration)

The cordova version of vendor.js gets generated using the following command:

`corber build --platform=ios --skip-cordova-build`

It seems this generates a vendor.js that differs substantially from the vendor.js produced by `ember serve` or `ember build`

Any ideas?

**Comment by alexblom** [comment]
I've just tried running `corber b` and then `ember b` and have a vendor.js of the same size. As a heads up `corber b` will *not* update dist/assets/vendor.js. Can you confirm if the asset sizes differ after explicit builds for each target?

I hate to ask - have you tried a nombom, and ensured `ember-cordova` is removed from package.json? Let me know if you'e already tried.

**Comment by pythonquick** [comment]
Thank you for the quick reply!

I tried again, with the following:

* removed node_modules and bower_components directories
* did a `npm cache clean` and `bower cache clean`
* did a `npm install && bower install`
* ran  `ember b` and got a warning of the node-sass module that it has to be rebuilt when running a new/different node version. I recently installed node 8. So I switched back to node 6 using the command `nvm use 6`. I'm using ember-cli 2.11.0
* ran `ember b` again with node 6. It produced a dist/assets/vendor.js file of 4.1 MB
* ran `corber b`. It produced a corber/cordova/www/assets/vendor.js file of 2.7 MB

Same result. I suspected it had to do with the different node versions on my system. So i uninstalled the node 8 using `nvm uninstall 8` and opened a new terminal window.

This time, the `corber b` command did not work - it could find the corber command! So it looks like corber was installed while i was on node 8. I reinstalled corber using `npm install -g corber` then built the app again:

* ran `ember b`. It produced a dist/assets/vendor.js file of 4.1 MB
* ran `corber b`. It produced a corber/cordova/www/assets/vendor.js file of 2.7 MB

Same result. One thing that is different between the two builds is that the `corber b` command produced the following warning which did not show up under `ember b`:

```
DEPRECATION: Addon files were detected in `/Users/myuser/Temp/myproject/node_modules/ember-resize-mixin/addon`, but no JavaScript preprocessors were found for `ember-resize-mixin`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-resize-mixin`'s `package.json`.
```

Anything else i can try?

**Comment by pythonquick** [comment]
yes, my package.json does not include ember-cordova (i removed it manually yesterday).
It does still include ember-cordova-events though.

**Comment by pythonquick** [comment]
My project was using ember-cli 2.11
After upgrading to ember-cli 2.16.2 the vendor.js file under corber/cordova/www/assets/ matched the dist/assets/vendor.js file.

Issue can be closed :-)

**Comment by alexblom** [comment]
Great - thanks. I'll document the minimum ember-cli version.
