### ISSUE TITLE
Update to cordova-lib 7.1.0

### ISSUE THREAD

**Issue by DuBistKomisch** [isleofcode/corber#421]
According to https://github.com/isleofcode/corber/commit/a100a22c52f39fc7d958a6fe6dfbf3ac4d48aadb it was locked to 7.0.1 because of removing deprecated APIs, but the fix has been merged according to https://github.com/isleofcode/corber/pull/386, so can it be updated? I'd like to be able to use the new support for `<config-file>` in `config.xml`.

**Comment by alexblom** [comment]
I'll be doing a release tomorrow, and will include the bump there. I've tested and seems fine on this end.
