### ISSUE TITLE
RFC: Introducing the start command, and corber 1.2

### ISSUE THREAD

**Issue by alexblom** [isleofcode/corber#428]
Hey Folks. The Isle team & myself have been busy working away at the next corber release, which includes emulator/device flashing as a first class citizen.

We wanted to open an Issue here to get your feedback on some of our proposed changes - and make sure we are supporting your use cases.

## Introducing `corber start`
```
corber start
corber start --emulator
corber start --emulator=‘iPhone X’
corber start --deviceid=‘uuid’
corber start --build
corber start --nobuild
```

The start command consolidates everything for local devflow. It’s a combination of our old build && serve commands with the addition of run. It:

1) Starts the livereload server by default;
	- Passing the build flag will instead produce a static build, similar to `corber b`;

2) Builds the native iOS/Android application;
3) Boots/starts/installs the app to an emulator/device;
— By default, installation will happen to an emulator;
— Emulators/devices can be targeted with:
	--emulator/--device will show a list of options to choose from;
        --if only one emulator/device is present we'll default to that device;
	--emulator=‘iPhone X’ will run on an iPhone X emulator; and
	--emulator=id || device=id will run on the target.

If you are interested, a demo video [is here](https://www.dropbox.com/s/ex86ep527p41d1w/start-cmd.mov?dl=0). In reality the command is faster - my computer seems to die when Quicktime recording. The WIP branch is here: https://github.com/isleofcode/corber/pull/412. Remaining work is cleaning up the start command, pending this discussion.

`corber start` will not require development teams or signing for emulator builds. Our hope is this should improve existing devflow, but also be more accessible to beginners. 

## corber build

Today, many users follow a workflow of running `corber build` and then using various techniques to run the app on a device/emulator.

We are hoping start will acommodate all of these cases. `corber build` will remain unchanged - but should only be used for generating signed/distributable builds.

## corber serve

With the introduction of start we’re not seeing many cases for serve that are not handled by `start`.

## Questions for the community

We’re interested in your general feedback here. Have we helped or hurt your use cases? What else would you like to see?

In addition, some pointed questions:
1) With the introduction of corber start, do you have any remaining use cases for serve in its current form?;
2) Are there any cases in the corber start flow where we can support you better?

## 1.2 release

The 1.2 release will be the first featuring the start command, initially for emulators. Later 1.2 releases will include support for physical iOS/Android devices.  From a library front, corber is creating iOS/Android `start` builds independent of cordova.

**Comment by DuBistKomisch** [comment]
This sounds great. My only question is if there's only one device present, will `--device` just use it straight away?

**Comment by alexblom** [comment]
@DuBistKomisch I see no reason why not. Editing to include it above.

**Comment by alexblom** [comment]
Closing given pending release.
