### ISSUE TITLE
Corber init error w/ React: `node_modules appears empty, you may need to run yarn install`

### ISSUE THREAD

**Issue by anulman** [isleofcode/corber#441]
Was helping a friend get started w/ React + Corber (using `create-react-app`). On a fresh app, when we ran `corber init`, we hit the following error:

```
node_modules appears empty, you may need to run yarn install
```

We traced the issue to the `Project.projectOrnullProject` invocation; if `closestSync` finds a non-ember-cli project, it sets `Project#pkg` to a blank object: https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L635-L638

To shim, we added a `require('fs')` to the frontmatter, and added a short check immediately after the `projectOrnullProject` invocation:

```
let project = Project.projectOrnullProject(ui, cli);
if (!project.isEmberCLIProject()) {
  let projectPackageJsonPath = path.join(project.root, 'package.json');
  let projectPackageJson = fs.readFileSync(, 'utf8');

  project.pkg = JSON.parse(projectPackageJson);
}
```

Happy to contrib the fix—maybe wrapping e-cli's `Project.projectOrnullProject` call with a package-level proxy?—but wanted to solicit feedback before implementing.

**Comment by alexblom** [comment]
Issue was traced to ember-cli not being installed on the machine - which is a case we need to better support.
