### ISSUE TITLE
Guide request: Working with Android Studio/Xcode

### ISSUE THREAD

**Issue by gossi** [isleofcode/corber#455]
I'm requesting these guides for the webpage under Workflow section (one for each IDE), because I'm kinda lost here, in which order I need to run which commands or which buttons I have to press and so on.

Things I wish would be covered here:
- Setup project in android studio/Xcode (also this is actually a no brainer, but a good start)
- Running `corber build` commands (as preparation for android studio commands)
- Working with devices (hardware you have laying around, connected to your dev machine)
  - Getting your prepared builds up on the device
  - Getting a serve build onto your device
  - For Android: shortcuts using `adb` - I do use it for my device since I think I'm faster with that, because I have less knowledge what might be the best of what I posted in the two items above 
- Working with emulators
  - Which `corber build` are suited commands and for what
  - How to get my code up on the emu - dealing with cache (I feel myself trapped, inspecting the same code over and over again, because I didn't get it updated against caches, although I changed it)

**Comment by alexblom** [comment]
Thanks for opening this. Just to leave a comment, I'm wrapping the `start` command which will give us a chance to update/rewrite docs with the new workflow.

**Comment by alexblom** [comment]
A little late to closing this issue, but Im hoping our updated workflow docs resolves this for you
