### ISSUE TITLE
Corber Start - Live Reload

### ISSUE THREAD

**Issue by nicwillemse** [isleofcode/corber#466]
Starting the emulator with `corner start` works perfectly, I have however noticed that the live reload stops working.

I can see that the build still runs when making changes, but the emulator simply does not reload.

Platform Details : 

`ember-cli: 3.0.0`
`node: 6.2.1`
`mac os `

I have only tried this with the iOS emulators. 

Please let me know if there are any other details you need or things you would like me to try.

**Comment by alexblom** [comment]
@nicwillemse Thanks for the report - I've admittedly not tested on ember-cli 3.x yet.

Are you familiar with remote inspection on iOS?

Would you mind sending me the following output from remote inspection:
- window.location (lets confirm it is pointed to the right place);
- If you manually type `window.location.reload()` do you see content refresh?;

Thanks for giving start a try.

**Comment by nicwillemse** [comment]
Hi @alexblom ,
No problem at all! 
window.location.reload reloads as expected, output from window.location below.  (Seems ok)

`Location = $1

ancestorOrigins: DOMStringList {length: 0, item: function, contains: function}

assign: function()

hash: ""

host: "10.10.1.37:4200"

hostname: "10.10.1.37"

href: "http://10.10.1.37:4200/"

origin: "http://10.10.1.37:4200"

pathname: "/"

port: "4200"

protocol: "http:"

reload: function()

replace: function()

search: ""

toString: function()

valueOf: function()

Symbol(Symbol.toPrimitive): undefined

Location Prototype
`

**Comment by nicwillemse** [comment]
@alexblom I have discovered something rather interesting, when launching the emulator from Xcode and running corber serve the live reload seems to work.

**Comment by alexblom** [comment]
Thanks @nicwillemse . I've managed to track down the issue - fix will be on master by eod. 

I aim to keep releases to Fridays but you should be ok pulling from master branch until then.

**Comment by nicwillemse** [comment]
Great- thanks @alexblom 

What was the spot cause ?
