### ISSUE TITLE
Cannot read property 'emulator' of undefined

### ISSUE THREAD

**Issue by betocantu93** [isleofcode/corber#469]
Trying to use live reload with corber start --platform=android and the following errors propmts

Cannot read property 'emulator' of undefined

The corber build --platform=android works without issues, any suggestion?

**Comment by alexblom** [comment]
Thanks for the report.

Does this error appear before emulators are listed, or on selection of an emulator? Also do you ever see emulators listed?

Thanks.

**Comment by betocantu93** [comment]
Hello thanks for your work, sorry for the late response, I was in a hackathon and fortunately it worked with corber serve.

I'm not sure what I'm supposed to see, I had Android Studio open and I ran corber start --platform=android on a separate terminal and nothing happened besides that error, by nothing I mean, no emulator list shown, (it's supposed to be shown? if so, how? prompt? in terminal or the typical Android Studio deployment target window, or...?)

**Comment by alexblom** [comment]
Thanks - if you didn't see any emulators listed I'll investigate from here.

And yes, we need to put some videos up. Running `corber start` will list available emulators/devices in your terminal window and then boot / install to the one you selected :)

**Comment by betocantu93** [comment]
Thanks @alexblom that would be great, let me know if you need a help with that, I'll be shipping my first ember cordova app soon, couldn't be happier, just... I'm still worried about some stuff about handling the lost of connection when requests have already started, would be epic if you can share a few tips, I've been looking your confs, but there's not much about the subject. Regards!

**Comment by ahmacleod** [comment]
Issue was resolved as of 1.2.4.
