### ISSUE TITLE
Corber: Cannot find module 'ember-cli-babel/package'

### ISSUE THREAD

**Issue by pollingj** [isleofcode/corber#482]
I'm getting this in my project at the moment.  `ember serve` runs fine, but `corber build` fails.

I was thinking it was one of my dependencies in the project, so created a completely blank ember project and ran `corber init`, and I get the same issue.

Is anyone else seeing this?

**Comment by pollingj** [comment]
Sorry, that was a dreadful submission.  

```
{
  "name": "corber-test",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for corber-test goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "corber": "1.2.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~2.17.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.1.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-data": "~2.17.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.17.0",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  }
}
```

That's the current package.json I'm using

**Comment by eguitarz** [comment]
I have the same issue. I use yarn (v1.5.1). After checking the `ember-cli` version in global corber's `node_modules`. The ember-cli version doesn't match the one I assigned in the project. For the workaround, I had to manually replace `ember-cli` in corber's `node_modules` for a correct version.

**Comment by eguitarz** [comment]
I had the same issue. You can simply fix it by upgrading your ember-cli in your project's package.json. (change `ember-cli` to `~2.18.0`, for example)
