### ISSUE TITLE
Cannot install corber with NPM

### ISSUE THREAD

**Issue by Pimnr47** [isleofcode/corber#483]
Hi,

When running npm install -g corber, as per the installation instructions, it fails to install because of a known error with Phantomjs 2.1.16. If fixed it by using npm install -g corber --ignore-scripts.

**Comment by alexblom** [comment]
Thanks for the report - do you have any links to the known issue? We've been debating making icons/splash a separate package to install, and this may be a great prompt to do so.

**Comment by ahmacleod** [comment]
Closing, as we were not able to reproduce this issue. If the problem persists, please open a new issue with exact os, node, npm, and corber versions.
