### ISSUE TITLE
Adjust Ember targets.js before building

### ISSUE THREAD

**Issue by hanssen** [isleofcode/corber#490]
When _corber_ builds the Ember application for a specific platform is should adjust the Ember `config/targets.js`. The mobile builds should i.e. not use the default `'ie 11'` flag. And Android would not need the `'last 1 Safari versions'`.

**Comment by alexblom** [comment]
Thanks again for reporting this - it is now supported as of 1.2.8. Some documentation can be found here: http://corber.io/pages/frameworks/ember

**Comment by hanssen** [comment]
Perfect, that's an elegant configuration! Thank you!
