### ISSUE TITLE
"Open is not supported for android"

### ISSUE THREAD

**Issue by AMS777** [isleofcode/corber#493]
When I run:
```
corber open --platform=android
```
I get this error:
```
Corber: Open is not supported for android
```
Android Studio is installed. Should it open?
> "ember-cli": "^3.1.3",
> "corber": "1.2.6",
> Android Studio 3.1.2
> JRE: 1.8.0

**Comment by alexblom** [comment]
Thanks for the report - this is expected unfortunately. We were unable to find a programatic way to open Android Studio directed to a project. I'd be very interested if somebody finds out how.

**Comment by AMS777** [comment]
Sorry to hear that. Unfortunately, I don't have the time right now to dive into it.
