### ISSUE TITLE
Capacitor and Corber

### ISSUE THREAD

**Issue by sandstrom** [isleofcode/corber#498]
Capacitor is a framework that labels itself as a 'spiritual successor' to Cordova, with backwards compatibility for many Cordova plugins.

We're currently using Corber + Cordova, but are eyeing Capacitor (still in alpha though).

Just curious if you have talked to someone on their team, or otherwise looked at their project. Just as Cordova supports multiple SPA-frameworks, perhaps there is room to support multiple frameworks on the other (native) side too?

https://capacitor.ionicframework.com/docs/

**Comment by ahmacleod** [comment]
Closing, as there is no action required here.

**Comment by sandstrom** [comment]
@ahmacleod Sounds good, agree this isn't that actionable 😄 Still interested in using Capacitor with Corber, I'll try to investigate it more when Capacitor is out of beta. 

Have a great weekend! 🌞
