### ISSUE TITLE
brand-new generated app doesn't load on iOS 9.3

### ISSUE THREAD

**Issue by kbullaughey** [isleofcode/corber#506]
I recently updated corber from 1.1.6 to 1.2.8 and now my app won't load on iOS 9.3. 

So in attempting to track down the issue, I created a new app using `ember new` with the latest stable build of ember-cli (3.1.4) and after the minimal updates to get the stock app to build (i.e., setting `locationType` to `hash` and `rootURL` to the empty string). The app works fine on 10.3 and 11.4, that is to say it shows the Ember welcome page. But when I load it in the 9.3 simulator it just shows a white screen and I can't see it in the Safari debugger. This is consistent with it failing very early. Unfortunately I'm at a loss as to the problem because nothing suspicious appears in the Xcode debugging console.

Has 9.3 support been discontinued? It seems that Cordova 4.5.4 is still supposed to support iOS 9.3.

**Comment by kbullaughey** [comment]
It seems the problem was simply that I needed to explicitly mention Safari 9 in my `config/targets.js`.

**Comment by adentranter** [comment]
@kbullaughey  could I please have a look at your config/targets.js?

**Comment by kbullaughey** [comment]
The important part for getting my app working on Safari 9 was to have `ios_saf >= 8` included in the list of browsers. When I know I'm building for iOS, I set this to be the only browser version specified in the browsers list. 

Here's my config/targets.js file:

    'use strict';

    let browsers = [
      'last 1 Chrome versions',
      'last 1 Firefox versions',
      'last 1 Safari versions'
    ];

    if (process.env.CORBER) {
      let platform = process.env.CORBER_PLATFORM || process.env.CORDOVA_PLATFORM || "ios";
      if (platform === "ios") {
        browsers = ['ios_saf >= 8'];
      }
    }

    module.exports = {
      browsers
    };
