### ISSUE TITLE
corber start: Corber: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by mcfiredrill** [isleofcode/corber#510]
Getting this error when I run `corber start`, any idea how I can get a backtrace or something?

```
☯tony@okirakugokiraku☯ ~/src/datafruits(corber *)$ corber start
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   DependencyVersionChecker.NPMDependencyVersionChecker (/Users/tony/src/datafruits/node_modules/ember-cli-rollbar/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)
Corber Starting
Corber: Cannot read property 'map' of undefined
```

btw my previous issue was fixed, thanks for that 🌟 
https://github.com/isleofcode/corber/issues/478

**Comment by alexblom** [comment]
Thanks for reporting. Just to confirm some basic things:
- Do you have Xcode installed, up to date;
- Can you confirm you've booted Xcode once to accept the licenses?;

Thanks!

**Comment by mcfiredrill** [comment]
Sorry for the late reply.
I have xcode 8.2.1 and yes I've booted it.

**Comment by alexblom** [comment]
No problems. Unfortunately you'll need to upgrade to the 9.x series of Xcode for the start command to work.
