### ISSUE TITLE
corber 1.3.0 does not build for production corrrectly

### ISSUE THREAD

**Issue by hoboman313** [isleofcode/corber#522]
Building Android + Windows + Ember with ```corber build --platform=android --environment=production --release``` no longer builds in production mode. Eg. assets are not minified and .maps are still present in the output .apk

edit: This issue is not specific to Android or Windows. 1.3.0 doesn't build properly for production on any environment.

**Comment by alexblom** [comment]
Thank you for the report. Resolution is a few days out but we know how to resolve

**Comment by hoboman313** [comment]
1.2.10 builds for production correctly for me. I see the corber/cordova/platform/*ios/android*/www/assets files get minified + uglified + source maps removed.

**Comment by woohoou** [comment]
I confirm 1.2.10 builds correctly, I apologize it was mistake with the version the broke version is 1.3.0

**Comment by patodevilla** [comment]
any updates on this issue?

**Comment by betocantu93** [comment]
+1

**Comment by alexblom** [comment]
This should be resolved as of 1.3.2 - sorry on the wait there.
