### ISSUE TITLE
Corber not removing old assets

### ISSUE THREAD

**Issue by kylemellander** [isleofcode/corber#528]
I noticed this when doing multiple builds for our cordova app (an ember app).  When it builds, it fingerprints the assets.  Then when they are copied over using the build-task, it keeps the old files.  I have had to manually remove the old assets in my framework.js, but it seems like this should not happen.

**Comment by kylemellander** [comment]
This is the line in question: https://github.com/isleofcode/corber/blob/master/lib/tasks/bash-build.js#L19

**Comment by alexblom** [comment]
Thanks for the report. Patching.

**Comment by alexblom** [comment]
Fixed in 1.3.2 :)
