### ISSUE TITLE
`corber start` not working in a fresh ember project

### ISSUE THREAD

**Issue by fpauser** [isleofcode/corber#529]
My env:
Linux 64
ember-cli-3.3.0
ember-3.3.1
corber-1.3.1.

I created a fresh ember project via `ember new mobile-app` and did a `corber init` selecting the android platform. All went fine, but doing a `corber start` just gives me

```
Corber Starting
Corber: Cannot read property 'find' of undefined
```

Java + Android studio is installed, a working emulator is present - any hints?

**Comment by alexblom** [comment]
Thank you. Can you try running `corber start --platform=android` and let me know if that is successful?

We default to iOS and I have a feeling we are missing a more readable error here.

**Comment by fpauser** [comment]
Same thing:

```
$ corber start --platform=android
Corber Starting
Corber: Cannot read property 'find' of undefined
```

**Comment by jelhan** [comment]
I'm facing the same issue on a project, which I have migrated from ember-cordova to corber.

`corber build --platform=android` and `corber proxy run android --emulator --nobuild` is working fine.

`corber start --platform=android` throws `Corber: Cannot read property 'find' of undefined`.

```
$ corber -v
corber (global): 1.3.2
corber (package.json): 1.3.2
corber (node_modules): 1.3.2
node: 8.11.4
```

```
$ cordova -v
8.0.0
```

```
$ ember -v
ember-cli: 2.18.2
node: 8.11.4
os: linux x64
```

**Comment by alexblom** [comment]
Thanks for the reports. We'll be spending a bit more time replicating / coming to a solution next week.

**Comment by alexblom** [comment]
I have a feeling this issue is limited to *nix envs, as I'm unable to replicate on Mac. I'm on the road and unfortunately won't have access to a proper nix env again for another ~week.

**Comment by alexblom** [comment]
Just to confirm, this was limited to *nix envs. I've got a working solution now - expect it on a Friday release. Cheers.

**Comment by alexblom** [comment]
1.3.3 is now live with these fixes
