### ISSUE TITLE
corber build: 'cp' is not recognised in Windows 10

### ISSUE THREAD

**Issue by osawyer** [isleofcode/corber#530]
Building Ember app from Windows fails
```
Built project successfully. Stored in "dist/".
'cp' is not recognized as an internal or external command,
operable program or batch file.
Corber: Command failed: cp -R ./dist/* corber/cordova/www
```
For Windows, should this use copy, not cp?

**Comment by CodePro212** [comment]
Wow, total amateur just use Underwriting

**Comment by alexblom** [comment]
Was there a constructive comment in there somewhere?

**Comment by osawyer** [comment]
Thanks @alexblom. Understandably, I might be missing something here which I'd be very grateful for being taught by a helpful soul.

**Comment by alexblom** [comment]
Hey it deletes his comments too, now I just look like a loonie. He could have been sharing his extensive skills with us vs you. 

I think think the issue is on our side, we need to improve Windows testing in general. I'll be able to confirm over the weekend/Monday.

**Comment by osawyer** [comment]
Haha many thanks!

**Comment by engwan** [comment]
Is there a temp workaround for this?

**Comment by osawyer** [comment]
Hi @engwan, in my project we are using GitLab CI with docker runners. This way the linux OS takes care of the build fine since it can use commands like 'rm' and 'cp'. But you could just setup a docker container on your local machine fairly quickly.

**Comment by osawyer** [comment]
Thanks for the update @alexblom, I'm very much looking forward to this being resolved!

**Comment by alexblom** [comment]
1.3.3 is now live with these fixes
