### ISSUE TITLE
Cannot fint module vue.config.js for Vue-CLI v2

### ISSUE THREAD

**Issue by Devoter** [isleofcode/corber#534]
When I try to build my app, I get this error:
`Corber: Cannot find module vue.config.js`

**Comment by alexblom** [comment]
Thanks for the report - do you mind confirming what version of vue-cli you are running?

**Comment by Devoter** [comment]
vue-cli version is 2.9.6

**Comment by alexblom** [comment]
Fixed in #550 

Docs updated here: http://corber.io/pages/frameworks/vue

Thanks!

**Comment by alexblom** [comment]
1.3.3 is now live with these fixes
