### ISSUE TITLE
Failed to load webpage with error: Frame load interrupted

### ISSUE THREAD

**Issue by MatthewPringle** [isleofcode/corber#536]
It seems that is ember starts routing before the splashscreen is hidden then the app will not load.

You are given this error "Failed to load webpage with error: Frame load interrupted"

I have found this to be happening because Ember Simple Auth routes an authenticated user when the app launches.

If the user has no token then the index page is loaded, however with a token the library tries to route the user to an authenticated route.

**Comment by MatthewPringle** [comment]
I didn't post this as an actual bug report for Corber, but hopefully other Corber users who are using Ember may find this useful.

My plan at the moment is to have an index page which waits until ember and cordova are loaded and which then redirects to the homepage / routes of the site which contain the auth & routing logic.

Hopefully by having a route that I can control, and which will not route to other pages, I can stop this issue before it happens.

**Comment by MatthewPringle** [comment]
If you are using ember-simple-auth you will need to have the deferReadiness run after ember-simple-auth as otherwise it will sometime fail to init the session.

` after: 'ember-simple-auth',`

```
/* App - Initializers - Cordova */
export function initialize( application ) {
    
    /* Device Ready */
    function onDeviceReady() {
        
        /* Resume Loading */
        application.advanceReadiness();
        
    }
    
    /* Cordova */
    if ( window.cordova !== undefined ) {
         
        /* Device Ready */
        document.addEventListener( 'deviceready' , onDeviceReady , false );
        
        /* Pause Loading */
        application.deferReadiness();
    
    }
    
}

/* Export */
export default {
    after: 'ember-simple-auth',
    initialize
};
```

**Comment by alexblom** [comment]
I'm going to close this as it seems to be less a corber bug, but hopefully other users can find this solution.

So we can check deeper, were you experiencing this issue with the `splashScreen` plugin?

Thanks.

**Comment by sanjivats** [comment]
https://swifttom.com/2021/09/18/failed-to-initialize-client-context-with-error-a-error-when-trying-to-run-a-widget-in-the-xcode-simulator-m1-macs/

Follow the steps.
