### ISSUE TITLE
TypeError: Cannot read property 'broccoliNode' of undefined

### ISSUE THREAD

**Issue by MatthewPringle** [isleofcode/corber#538]
I updated Corber to latest and it now generates the following errors. Removed all npm, installed Ember again ember-cli 3.1.4

Installed Corber and the following still happens when trying to test on simulator.

XCode 9 as 10 causes other issues

=================================================================================

ENV Summary:

  TIME: Mon Sep 24 2018 16:48:41 GMT+0100 (BST)
  TITLE: corber
  ARGV:
  - /usr/local/bin/node
  - /Users/matt/.npm-global/bin/corber
  - start
  - --environment=development
  - --platform=ios
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/4v/tr3wcx8540n4t_06mc93gfyr0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Users/matt/.npm-global/bin
  - /Users/matt/Library/Android/sdk/tools
  - /Users/matt/Library/Android/sdk/platform-tools
  - /Users/matt/.npm-global/bin
  - /Users/matt/Library/Android/sdk/tools
  - /Users/matt/Library/Android/sdk/platform-tools
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 78938112
  TOTALMEM: 17179869184
  UPTIME: 1980
  LOADAVG: 2.60595703125,2.591796875,2.55712890625
  CPUS:
  - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz - 3800
  - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz - 3800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.12.0
  - openssl: 1.0.2p
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.2
  - v8: 6.2.414.66
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'writeLine' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'writeLine' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'writeLine' of undefined
    at Watcher.didChange (/Users/matt/Sites/my-fluent/node_modules/corber/node_modules/ember-cli/lib/models/watcher.js:47:13)
    at emitOne (events.js:121:20)
    at Watcher.emit (events.js:211:7)
    at Watcher.triggerChange (/Users/matt/Sites/my-fluent/node_modules/ember-cli-broccoli-sane-watcher/index.js:174:8)
    at tryCatcher (/Users/matt/Sites/my-fluent/node_modules/corber/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/matt/Sites/my-fluent/node_modules/corber/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/Users/matt/Sites/my-fluent/node_modules/corber/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (/Users/matt/Sites/my-fluent/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

=================================================================================

**Comment by MatthewPringle** [comment]
Thinking it has something to do with the below, which happens after I update Corber to 1.3.2 on my laptop, without changing anything else on the computer.

babel-plugin-debug-macros@0.2.0-beta.6 requires a peer of @babel/core@^7.0.0-beta.42

**Comment by conormag** [comment]
I had this issue. typing `corber -v` in my project's root folder showed I had v1.3.2 installed globally but 1.2.9 was listed in projects's package.json. Updating that to 1.3.2 fixed the issue.

**Comment by alexblom** [comment]
Thanks @conormag. 

As of 1.3.x you will need both your project and global corber versions to be on the 1.3.x series. 

Can you confirm if this fixes the issue for you, @MatthewPringle

**Comment by MatthewPringle** [comment]
@alexblom I have found removing both Ember and Corber globally, then installing Ember then Corber globally, then npm install in the project fixes all the issues.

Done this on 2 computers now, updating didn't work.

**Comment by alexblom** [comment]
I'm glad that issue is resolved - I'm going to add a debug message to our next build alerting anybody else who may be struggling.

Thanks for sticking with us through that one!
