### ISSUE TITLE
No Node 9 support for corber-ember-livereload

### ISSUE THREAD

**Issue by conormag** [isleofcode/corber#539]
Corber 1.3.0 introduced a dependency on corber-ember-livereload.

corber runs on node >=4.5
corber-ember-livereload runs on node 6 || 8 || 10

can corber-ember-livereload be updated to node >= 4.5?

I'm adding this here as cant find a repository for corber-ember-livereload.

**Comment by conormag** [comment]
closing - corber-ember-livereload is not required any more

**Comment by MatthewPringle** [comment]
Hey @conormag what do you mean "corber-ember-livereload is not required any more"

I have just installed 1.3.2 and it installs corber-ember-livereload on init.

But it doesn't seems to work as I cant see the cordova.js file anywhere and plugins are not working.

**Comment by alexblom** [comment]
Hmm, is your project ember @MatthewPringle .

I've seen another report here, I need to sit down and re-init a new project to confirm the injection is working. It's fine on the test projects I have, so I need to dig in a bit further.

**Comment by MatthewPringle** [comment]
Yes Ember.

1.2.9 worked fine and I had no issues with that at all.

I have never been able to get 1.3.2 working until just now, I saw a post from Conormag above about having different versions installed. I think I updated initially.

Anyway I removed Corber globally, deleted the local node_modules folder and did a fresh npm install.

That seems to have worked, with no need for init as live reload was installed. I can delete and repeat and it does work.

Having updated Ember, Corber and the different dependencies maybe something went wrong.

My only issue now is that config.xml gets multiple lines of the injected path, they are never removed or overwritten as before. Which is odd.

<allow-navigation href="http://192.168.1.56:4200" name="ec-nav" />
<allow-navigation href="http://192.168.1.56:4200" name="ec-nav" />

Thanks for your work in getting Ember into Cordova like you have. It has made development a breeze!

```
"dependencies": {
    "aws-sdk": "^2.278.1",
    "inputmask": "^4.0.0",
    "mobile-detect": "^1.4.2",
    "slick-carousel": "^1.8.1"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.7.0",
    "corber": "1.2.9",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~3.1.4",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-content-for-index": "^0.1.2",
    "ember-cli-content-security-policy": "^1.0.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-qunit": "^4.3.2",
    "ember-cli-sass": "^7.1.7",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-concurrency": "^0.8.19",
    "ember-cordova-events": "^0.1.1",
    "ember-cordova-splash": "^0.1.8",
    "ember-cp-validations": "^4.0.0-beta.1",
    "ember-data": "~3.2.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-moment": "^7.7.0",
    "ember-resolver": "^4.0.0",
    "ember-simple-auth": "^1.7.0",
    "ember-source": "~3.2.0",
    "eslint-plugin-ember": "^5.0.0",
    "loader.js": "^4.2.3",
    "qunit-dom": "^0.6.2"
  },
```

```
"dependencies": {
    "@babel/core": "^7.1.2",
    "aws-sdk": "^2.327.0",
    "inputmask": "^4.0.2",
    "mobile-detect": "^1.4.3",
    "node-sass": "^4.9.3",
    "slick-carousel": "^1.8.1"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^3.0.0",
    "corber": "^1.3.2",
    "corber-ember-livereload": "0.0.1",
    "ember-ajax": "^3.1.1",
    "ember-cli": "~3.4.3",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.7.1",
    "ember-cli-content-for-index": "^0.1.2",
    "ember-cli-content-security-policy": "^1.0.0",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^3.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.4",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-qunit": "^4.3.2",
    "ember-cli-sanitize-html": "^2.0.2",
    "ember-cli-sass": "^8.0.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-concurrency": "^0.8.21",
    "ember-cordova-events": "^0.1.2",
    "ember-cordova-splash": "^0.1.8",
    "ember-cp-validations": "^4.0.0-beta.2",
    "ember-data": "^3.4.2",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-moment": "^7.8.0",
    "ember-resolver": "^5.0.1",
    "ember-simple-auth": "^1.7.0",
    "ember-source": "~3.4.4",
    "eslint-plugin-ember": "^5.0.0",
    "loader.js": "^4.2.3",
    "qunit-dom": "^0.8.0",
    "sass": "^1.14.1"
  },
```

**Comment by alexblom** [comment]
Thanks - I've created #540 to track that issue

**Comment by conormag** [comment]
@MatthewPringle Sorry Matthew, you're right. I was down a very deep hole at the time and realised my mistake after but forgot to update this issue. I'm reopening the issue as the problem still stands as stated. Hopefully @alexblom can get to it at some stage.

**Comment by alexblom** [comment]
Thanks, the corber-ember-livereload node version has been extended. 

If you have already initted your project you will need to manually force the version to 0.0.2+.
