### ISSUE TITLE
Won't build for platform=android, JDK version too new?

### ISSUE THREAD

**Issue by eelke** [isleofcode/corber#544]
Hi there, I'm stuck in a loop between adding and being unable to use Corber with the Android platform. Long post, as I try to document it as well as I can. 

When I try to use the platform, corber says it's not installed:

```
$ corber start --platform=android
[[...removed: deprecation warning*...]]
Corber Starting
Corber:
        You are passing platform=android which is not installed.
        Try running corber platform add android 
```

However, it IS installed. Trying to add the platform yields:

``` 
$ corber platform add android
[[...removed: deprecation warning*...]]
Preparing to add platform android
Using cordova-fetch for cordova-android@^7.1.1
Corber: Platform android already added.
```

And when I then try to start it again, it still doesn't work:

``` 
$ corber start --platform=android
[[...removed: deprecation warning*...]]
Corber Starting
Corber:
        You are passing platform=android which is not installed.
        Try running corber platform add android
```

Et cetera et cetera.

When I run `corber build --platform=android` I get a little bit more information though:

```
(... building Ember app code..) 
Built project successfully. Stored in "dist/".
corber: Setting up corber/cordova/www/index.html...

Android Studio project detected
config file *-Info.plist requested for changes not found at /Users/eelke/Documents/Werk/Server/mondriaan-route/corber/cordova/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/eelke/Documents/Werk/Server/mondriaan-route/corber/cordova/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/eelke/Documents/Werk/Server/mondriaan-route/corber/cordova/platforms/android/*-Info.plist, ignoring
ANDROID_HOME=/Users/eelke/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
Corber: Requirements check failed for JDK 1.8

```

I have a brand new Ember project + a new installation of Corber. I have also followed all the steps in the Android Setup: Android Studio is installed, with a virtual machine, and I have actually been able to compile and run another project inside the VM. 

`corber start` _does_ work with iOS and the iOS simulator. And I have also been able to build a project (using `corber build` – no specific platform set), followed by manually importing and building the project from `corber/cordova/platforms/android/` into Android Studio. 

My setup: 

```$ ember -v
ember-cli: 3.5.0
node: 8.12.0
os: darwin x64 
```

```
corber -v
[[...removed: deprecation warning*...]]
corber (global): 1.3.2
corber (package.json): ^1.3.2
corber (node_modules): 1.3.2
node: 8.12.0
```

I have added the to ~/.profile:
```
export PATH=$PATH:/Users/eelke/Library/Android/sdk/platform-tools
export PATH=$PATH:/Users/eelke/Library/Android/sdk/tools
export ANDROID_HOME=/Users/eelke/Library/Android/sdk
```
And these show up correctly when I run both `echo $PATH` and `echo $ANDROID_HOME`. 

Any suggestions?

---

*)  The deprecation warning is: `DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/eelke/.config/yarn/global/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)`

**Comment by alexblom** [comment]
Thanks for reporting this - updating the documentation now.
