### ISSUE TITLE
Some of the documentation pages are not accessible

### ISSUE THREAD

**Issue by papakay** [isleofcode/corber#554]
I tried accessing some of the documentation pages but it returned EMPTY_RESPONSE error.

Some of the pages include http://corber.io/pages/ember-cordova-migration.html

Please can you kindly help look into this.

**Comment by alexblom** [comment]
Could it have been a blip with gh-pages? I was just able to load http://corber.io/pages/ember-cordova-migration.html

**Comment by papakay** [comment]
I've tried it again without any luck on several browsers.

Please see the attached screenshot.

<img width="1271" alt="screenshot 2018-11-27 at 8 42 11 pm" src="https://user-images.githubusercontent.com/5013738/49107075-10217380-f285-11e8-8b45-58ccf560729c.png">

**Comment by alexblom** [comment]
I'm honestly stumped as to what this could be - loads fine for me. Is anybody else encountering this issue?

**Comment by papakay** [comment]
Thanks so much @alexblom , i found out today that the issue was from my macbook. It has nothing to do with the documentation pages. Please accept my apologies.

Thanks so much.

**Comment by alexblom** [comment]
No problems - glad you can view them now :)
