### ISSUE TITLE
Xcode 10 support, passing build args to cordova 

### ISSUE THREAD

**Issue by billdami** [isleofcode/corber#563]
When attempting a `corber build --platform=ios --environment=development` on macOS Mojave v10.14.1 (Xcode v10.1), I am getting the following error:

```
error: archive not found at path '/path/to/my-project/corber/cordova/platforms/ios/my-project.xcarchive'
** EXPORT FAILED **
```
In the ios build directory, I can see that there is indeed no `.xarchive` file generated.

Some searching lead me to this SO answer:
https://stackoverflow.com/a/52400072/192694

But im not sure how (or if its possible) to send additional cordova-only build args via `corber build`. I tried the following:

```
corber build --platform=ios --environment=development --buildFlag="-UseModernBuildSystem=0"
```
and
```
corber build --platform=ios --environment=development -- --buildFlag="-UseModernBuildSystem=0"
```
But neither have any effect. Is this the correct solution, or does corber/cordova already support Xcode 10, and this is a different issue?

**Comment by billdami** [comment]
disregard, was able to resolve this by enabling the "Legacy Build System" as my default preference directly in Xcode.

**Comment by ELLIOTTCABLE** [comment]
Do note that this can be done without monkeying around Xcode directly, too — add it to `corber/cordova/build.json`, and commit that to version-control. Ours looks something like this:

```json
{
    "ios": {
        "debug": {
            "codeSignIdentity": "iPhone Developer",
            "developmentTeam": "<TEAM ID>",
            "packageType": "development",
            "automaticProvisioning": true,
            "buildFlag": [
                "-UseModernBuildSystem=0",
                "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
                "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
                "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
            ]
        },
        "release": {
            "codeSignIdentity": "iPhone Developer",
            "developmentTeam": "<TEAM ID>",
            "packageType": "enterprise",
            "automaticProvisioning": true,
            "buildFlag": [
                "-UseModernBuildSystem=0",
                "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
                "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
                "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
            ]
        }
    }
}
```
