### ISSUE TITLE
Ember: only change rootURL and locationType during a Corber build

### ISSUE THREAD

**Issue by christophersansone** [isleofcode/corber#565]
I think this is really just a documentation change for consideration.

When building a Corber app with Ember, the [docs](http://corber.io/pages/frameworks/ember) say to change the `locationType` to `hash` and to make sure `rootURL` and `baseURL` does not have a leading slash (which it does by default).  It would be nice if these requirements were only when building the mobile app rather than at all times.  I tend to think most people would prefer the Ember defaults if possible.

I adjusted my `config/environment.js` as follows, and it seems to work:

```javascript
    rootURL: process.env.CORBER ? '' : '/',
    locationType: process.env.CORBER ? 'hash' : 'auto',
```

When building the mobile app (as determined by the existence of the `CORBER` environment variable), it will use the values required by Corber.  When building any other time, it will use the Ember defaults (or whatever you want).

Happy to make the change myself if it's the right way to go.

**Comment by alexblom** [comment]
Thanks @christophersansone ! I'd happily accept those doc changes.

**Comment by alexblom** [comment]
I need to spend more time thinking about it but didn't want to leave this hanging. We're in a bit of a bind that in cordova we _must_ have a hash. Most of the time I just enforce that on the webapp as well but get your challenge and we should find a solution. 

I use a similar technique where any <img> tag in an Ember app will be <img src="{{rootUrl}}/foo"}} instead off <img src="foo">. I was unaware this property was not available in templates - is this something that has changed or am I confusing baseURL?

**Comment by christophersansone** [comment]
`{{rootUrl}}` is not listed as a property of Component or Controller, and it is not a built-in template helper, so I don't think that would work today.  {{baseURL}} is no longer a thing since [this deprecation](https://www.emberjs.com/blog/2016/04/28/baseURL.html) in Ember 2.7.  An easy solution is to just use the `<base>` tag, which I believe is how Ember used to do it, but the deprecation documentation recommends against it due to some edge cases (albeit that was two years ago).

It does seem like prepending `{{route-url}}` or doing a Rails-like `{{path-for 'assets/images/logo.png'}}` is the right way according to the current state of Ember.  We can get crazy and use a linter to find places where it looks like a relative path is being used without it, or we can automagically fix them... but again, I'm just not sure it's worth the hassle unless you REALLY care about not having hash routing.

**Comment by alexblom** [comment]
I've been thinking about this a bit more. I think for now we should keep hash routing as the suggested path (easier for new people) but add your solution to our ember docs page (here: https://github.com/isleofcode/corber/blob/gh-pages/pages/frameworks/ember.md) for more advanced users?

At that point we can also drop the hash routing validator from throwing an error to a warning.

How does that sit with you?

**Comment by christophersansone** [comment]
@alexblom Sorry I never responded, I just felt it became too complex to offer it as a standard way to implement.  I'm successfully doing it in production with everything described above, so it can be done... it's just too far off the happy path to recommend it.  Hopefully if anyone else is wondering how to do it, they stumble across this issue. :smile:
