### ISSUE TITLE
Feature request: start command loads platform-dependent cordova.js-file

### ISSUE THREAD

**Issue by NiklasWebnuts** [isleofcode/corber#566]
Currently, when you run `corber start`, an emulator will be launched (e.g. an Android emulator), and an ember server will run, serving the content for the app to use. However, the entire Cordova framework is not available in this case. Would it be possible to inject this somehow, such that we'll be able to use the awesome live reload functionality and still use the Cordova framework?

**Comment by NiklasWebnuts** [comment]
Looks like i've misconfigured my project. I've just tried with a fresh installation, and here the cordova.js file seems to be embedded in the vendor.js-file. I'll have to do some debugging in my project to figure out what I've done wrong. Sorry for the inconvenience.

**Comment by alexblom** [comment]
No problems - let me know if there's a validator we should add once you figure it out :)
