### ISSUE TITLE
Infinite gap://ready and xdg-open

### ISSUE THREAD

**Issue by Devoter** [isleofcode/corber#568]
I've been updated corber from 1.2.7 to 1.3.3 and have been suprised. If I open an application in Chrome on my desktop, I see xdg-open popup which could not be closed. In the network tab of devtools I have many requests `gap://ready`.

Corber: 1.3.3
Vue: 2.5.21 (Vue CLI 3)
Command: `npx corber server --platform=android`

**Comment by alexblom** [comment]
Hi There,

Having trouble replicating this one. Do you mind confirming a few things for me:

1) If you can access the source of the page while livereloading, do you see script tags for cordova.js and cordova_plugins.js?;
2) Which platform are you building for (ios/android);

Thanks!
