### ISSUE TITLE
"file" argument must be a non-empty string

### ISSUE THREAD

**Issue by rDuckDev** [isleofcode/corber#580]
Running `corber start --platform=android` results in two lines stating '"file" argument must be a non-empty string'.

Log is on a different machine, but snippets include:

> -- broccoliBuilderErrorStack
> ...
> -- stack: typeError: "file" argument must be a non-empty string
>   at normalizeSpawnArguments (child_process.js:389:11)
> ...

Running `ember serve` works fine.

Running `corber serve` says to run `corber plugin add cordova-plugin-whitelist` (also printed twice, like the earlier message).  I've done that three times (CLI reports successful install), but message does not go away.

Any help is appreciated.

NodeJS v8.15.0
Windows 10

**Comment by conormag** [comment]
regarding the `corber serve` issue, when that command is run without params it will attempt to serve the ios version of your build. Given you are on Windows and not Mac, thats unlikely to work?

**Comment by rDuckDev** [comment]
`corber serve --platform=android` works like a charm when navigating to http://localhost:4200 in my browser, thanks!  That does break **Run 'app'** in Android Studio, though.

**Comment by JoepHeijnen** [comment]
Same issue here. I can't get it running on my emulator

**Comment by rDuckDev** [comment]
@JoepHeijnen, try the following:

```PowerShell
# make sure Android Studio is open to the corber project (it handles Gradle builds, I believe)
corber serve --platform=android

# make sure you have your AVD running,
# then in a second terminal window
corber proxy run android
```

It doesn't solve the actual issue, but it is a suitable workaround in the meantime.
