### ISSUE TITLE
Navigator empty object on iOS

### ISSUE THREAD

**Issue by BHuys** [isleofcode/corber#582]
I'm using corber to make an iOS/Android project using emberJS codebase. When I deploy my app on android devices I don't get any problems, when I deploy on iOS it seems that my "navigator" object is empty.

**Comment by alexblom** [comment]
I notice you closed this - just wanted to ensure all was ok on your side?

**Comment by BHuys** [comment]
My bad, after some research I found out that iOS safari simply didn't support what I needed, making this issue irrelevant.
