### ISSUE TITLE
webpack file naming issues

### ISSUE THREAD

**Issue by kbrownlees** [isleofcode/corber#584]
I have just been integrating corber with a custom webpack setup and came across a couple of gotchas.

    "corber": "^1.3.3",
    "corber-webpack-plugin": "^1.0.0",
    "webpack": "^4.29.3",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"

I had an issue where the cordova javascript files were being served as 'name.js.js', it seems that by default webpack has output.filename = '[name].js'. And the corber-webpack-plugin provides name as 'cordova.js'. Hence you end up with 'cordova.js.js'.

The second issue was the name on the cordova plugin files appear to be wrong, it is providing the full path from the CWD as the 'name' to webpack. Eg: `corber/cordova/platforms/ios/www/plugins/cordova-plugin-file/www/ProgressEvent.js`. It should be relative to the cdvAssets path Eg: `plugins/cordova-plugin-file/www/ProgressEvent.js`.

The first issue can be worked around by doing something like:

    entry: {
        "bundle.js": path.resolve(ROOT_DIR, "src", "app.js")
    },
    output: {
        filename: "[name]",
        path: path.resolve(ROOT_DIR, 'build')
    },

The second issue is harder to work around. Is there something in a basic setup which I am missing?

**Comment by alexblom** [comment]
Thanks for the report here - I'm still working on a resolution that is stable on generic webpack & Vue CLI.

Just a quick confirmation - you should only be encountering this problem during `serve` and `start`, but not during `build`?

**Comment by kbrownlees** [comment]
Yeah this is an issue with the 'CorberWebpackPlugin', which is serve / start only I believe.

**Comment by alexblom** [comment]
Thanks for the comment / patch. I'll be giving it a QA on my side for release asap. 

It can unfortunately take a little while to test across webpack generic / react / vue-cli. Unfortunately that part of our stack has been very tough to write testing for :-)

**Comment by kbrownlees** [comment]
Is a bit of a hack, not sure how well it would hold up under different situations. The other option here is to copy the required files into the build folder so they get served like static files. I am sure that also has some edge cases, but would probably be nicer for my setup.

**Comment by alexblom** [comment]
We've had trouble historically with copying the files. Once we are running in a cordova shell - even for start - it is best to leave them in place and link relatively. 

I'm working on a deeper solution /w Vue-CLI, hopefully will have time to wrap in a few more days. From there we can potentially merge your solution for more generic webpack cases :-)

**Comment by alexblom** [comment]
Just a heads up, I've released `vue-cli-plugin-corber` for Vue users now.

That clears me up to merge your changes for pure Webpack. I owe it a QA and expect a merge next week. Thanks!

**Comment by alexblom** [comment]
FYI - feel free to submit these changes directly on the webpack plugin. Thanks.
