### ISSUE TITLE
corber/cordova/www/.gitkeep deleted when building

### ISSUE THREAD

**Issue by DuBistKomisch** [isleofcode/corber#590]
Seems to be introduced in 1.3.3 with https://github.com/isleofcode/corber/commit/05b571a2 since it now "empties" the output directory.

**Comment by alexblom** [comment]
Thanks! We started deliberately emptying the directory for a corber build/output as we found people were not re-building. Given our builds include mobile assets it was causing some confusion.

Perhaps we should re-evaluate that, but in the interim whitelist .gitkeep for deletion?
