### ISSUE TITLE
corber installation fails on Phantomjs

### ISSUE THREAD

**Issue by sdelrue** [isleofcode/corber#591]
I get this error when installing corber (same as #483)  : 

`Removing /usr/local/lib/node_modules/corber/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1550495985462/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/corber/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/local/lib/node_modules/corber/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/corber/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ocular/.npm/_logs/2019-02-18T13_19_49_655Z-debug.log
MacBook-Air-van-Maxime:ergosleep-mobile-app ocular$ sudo npm install -g corber --ignore-scripts
npm WARN deprecated exists-sync@0.0.4: Please replace with usage of fs.existsSync
npm WARN deprecated exists-sync@0.0.3: Please replace with usage of fs.existsSync
/usr/local/bin/corber -> /usr/local/lib/node_modules/corber/bin/corber
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.`

npm install -g corber --ignore-scripts does work

osx 10.14.3
corber@1.3.8
node v10.15.1
npm 6.4.1

**Comment by alexblom** [comment]
Thanks for reporting - unfortunately I'm not able to replicate over here.

The good news is we're taking steps to move icons/splash out of the mainline repo which will let us drop phantom as a dependency.

**Comment by tdiddi** [comment]
try adding `--unsafe-perm`.

fixed it for me on ubuntu 18.10

**Comment by alexblom** [comment]
I think this is our solution for now. Hopefully an update in the coming weeks where we'll have taken these features out of the main repo.

**Comment by rodrigoyoshida** [comment]
Tried to install Corber but had a PhantomJS issue too. I had to use the `--unsafe-perm` but I'm afraid that it can cause me some problems in the future.

**Comment by rodrigoyoshida** [comment]
Opened a new issue about it since this one is closed. 

https://github.com/isleofcode/corber/issues/637
