### ISSUE TITLE
--verbose flag doesn't work with build command when platform defaults to android

### ISSUE THREAD

**Issue by DuBistKomisch** [isleofcode/corber#601]
It works when I pass `--platform android` as well, so this is pretty weird. Haven't tested if this also happens with mac defaulting to ios.

**Comment by alexblom** [comment]
Can you confirm if this is still replicate-able on 1.3.10?

You may need to upgrade both your global CLI & projects version of corber.

Thanks!

**Comment by DuBistKomisch** [comment]
Can't test either way, it doesn't seem to build android without the --platform flag on 1.3.10 now.

**Comment by alexblom** [comment]
That seems like a bug. If you only have one platform installed that platform will be used as a default.

I've just run a test on 1.3.10 and unfortunately could not replicate. In an Ember/Corber project with only Android, verbose logs appeared for `corber build --verbose` and `corber build --platform=android --verbose`

Do you mind pasting the output of `corber version` so I can debug further?

Cheers!

**Comment by DuBistKomisch** [comment]
This was in a project with ios and android platforms, running on Linux.

```
 $ npx corber version
corber (global): 1.3.10
corber (package.json): 1.3.10
corber (node_modules): 1.3.10
node: 8.16.0
```
