### ISSUE TITLE
update docs to refer to ANDROID_SDK_ROOT instead of ANDROID_HOME

### ISSUE THREAD

**Issue by gmkohler** [isleofcode/corber#605]
The android platform setup documentations recommend setting `ANDROID_HOME` but the [android developer guides]((https://developer.android.com/studio/command-line/variables#envar)) indicate that this is deprecated, as do the logs when running `corber build --platform=android`:

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/Users/kohler/Library/Android/sdk (DEPRECATED)
```

I don't know much about whether this is relevant for corber given it's still on an older JDK but thought I would bring it to your attention in case it is something that can be changed.

**Comment by alexblom** [comment]
Fixed - thank you!
