### ISSUE TITLE
Suggestion - Vue Documentation

### ISSUE THREAD

**Issue by caiokawasaki** [isleofcode/corber#610]
Inside my vue.config.js if I put the following code: `baseUrl: './'`.

If I run `npm run serve` to develop without focusing the android or ios things get weird...

The hot reload stop working and my routes do not work if I try to access them directly, I always need to start from the root route.

To `fix` this, I changed it to the following: `baseUrl: process.env.NODE_ENV == 'app' ? './' : '/'`

And everything is clear again.

So when I need to build the app, inside my .env file I change the `NODE_ENV` variable to app then run the following command: `corber build --environment=production --platform=android --release`

This should be on documentation?

**Comment by alexblom** [comment]
Agreed. We also do expose a CORBER var in process.env if you'd prefer to detect that way.

I'll add the changes to docs on the next release. If you want to beat me to it, we host all of the docs in this repo on the gh-pages branch.

Thanks for the report!
