### ISSUE TITLE
Android Setup Guide dead compatibility link

### ISSUE THREAD

**Issue by AndrewDant** [isleofcode/corber#611]
In the docs, specifically the Android Setup guide (http://corber.io/pages/android-setup), there is a broken link to "compatibility." Clicking the link gives a 404 screen. It is at the end of the second sentence under the "Setting up emulators for corber start" section. The link is to corber.io/compatibility

**Comment by alexblom** [comment]
Thanks! I just removed the link - we were using that when start was newer and not yet supporting all platforms.
