### ISSUE TITLE
Ember Vibration

### ISSUE THREAD

**Issue by ChristopherJohnson25** [isleofcode/corber#616]
Does anyone have a quick example on how to use vibration with Corber? I'm jumping straight into Corber without experience in Cordova, so a quick example would be awesome. 

Additionally (I'd rather not clog up the issues if I don't have to), is fullscreen without the status bar on Ember something simple? Can't seem to find this anywhere in the docs.

**Comment by ddoria921** [comment]
> is fullscreen without the status bar on Ember something simple?

Are you referring to full screen on the newer iPhones (i.e the ones with the notch)?

**Comment by conormag** [comment]
It would be much better to ask these questions on [corber.slack.com](https://corber.slack.com)
