### ISSUE TITLE
Corber support for Android 9 API level 28

### ISSUE THREAD

**Issue by caltabid** [isleofcode/corber#619]
When Android 9.0 will be supported?
Starting August 1, 2019, Google Play requires that new apps target at least Android 9.0 (API level 28), and that app updates target Android 9.0 from November 1, 2019.

**Comment by MatthewPringle** [comment]
An update for this would be nice as otherwise it is looking that from November we might me screwed!

**Comment by alexblom** [comment]
Resolved as of 1.13.12 - will be out later today.
