### ISSUE TITLE
Corber support for Cordova 9

### ISSUE THREAD

**Issue by c-emil** [isleofcode/corber#620]
First, I'd like to say that you've done a great job on this. For example, live reload is just amazing feature that saves tons of time. And now back to my question, are there any plans to support Cordova 9 in near future? Some plugins don't even work with Cordova 8.x. For example, the latest version of cordova-plugin-intercom supports only Cordova >=9. Thanks!

**Comment by jl-cs** [comment]
This would really be appreciated.

**Comment by alexblom** [comment]
Resolved in 1.13.12 - out later today.
