### ISSUE TITLE
reloadUrl in ember-cli config is ignored

### ISSUE THREAD

**Issue by c-emil** [isleofcode/corber#621]
I have `reloadUrl` set up in my ember-cli config to `http://localhost:4203` and when I run `cober serve` or `corber start`, it adds my local network IP address with correct port (because I have port set up in framework.js as well) to `config.xml` instead of `localhost:4203`. It does livereload though, so it's actually working, it's just confusing that it adds the IP instead of `localhost`.

**Comment by alexblom** [comment]
Thanks. The reloadUrl is generated - however you can pass a reloadUrl directly with your command which will override our generated url. Let me know if that helps.
