### ISSUE TITLE
Repo Abandoned?

### ISSUE THREAD

**Issue by MatthewPringle** [isleofcode/corber#626]
Hey Alex

Firstly thanks for all the work on this.

As updates have gone quite for a few months and with Android starting to enforce higher api versions than Corber supports can I ask if this repo is going to be updated?

If not I think people need to know sooner rather than later so they can start to make alternate plans in terms of publishing new apps and supporting older ones.

**Comment by alexblom** [comment]
It is not. Have not had a chance to handle the android upgrades yet - it ties in to a set of issues with Ubuntu compilation which need to be fixed at the same time. 

There is typically only a few days per month for these maintenance upgrades, simply have not had the time yet. 

Thanks
