### ISSUE TITLE
corber plugin add not saving to config.xml

### ISSUE THREAD

**Issue by wongpeiyi** [isleofcode/corber#632]
Using 1.4.0, I get no visible errors doing

```
corber plugin add cordova-plugin-device

attempting to add plugin 'cordova-plugin-device'...
action completed
```
but config.xml is not updated with the plugin

- I have another repo at 1.3.11 and it does still work
- I created a brand new ember app, ran `corber init` (1.4), and above `plugin add` and config.xml is not updated
- It works if I downgrade global corber to 1.3.11

Could you look into this or give me a direction to debug?

**Comment by alexblom** [comment]
Can you confirm if it is in your Cordova package.json?

**Comment by ChristopherJohnson25** [comment]
Just came across this as well...

**Comment by wongpeiyi** [comment]
Hey @alexblom, yes it is in the cordova package.json, only missing from config.xml

**Comment by alexblom** [comment]
This should not be a concern as of corber 1.4.0 due to upstream Cordova upgrades.

More modern cordova versions generally use package.json for plugins, and the config.xml is used more for storing more complex plugin config information. `corber/cordova prepare` should still work as well. 

Cheers!

**Comment by wongpeiyi** [comment]
@alexblom I don't get it – package.json is in .gitignore, so if I do any git checking out, or even hand my repo to a colleague, they have zero committed information about the plugins I installed? How does `corber prepare` work if both config.xml and package.json is blank?

Can you please elaborate further?

**Comment by alexblom** [comment]
That is an issue on our side - in prior versions we did need to ignore the file. I'll update that in the next day or two - cheers.
