### ISSUE TITLE
Corber Start Error

### ISSUE THREAD

**Issue by devotox** [isleofcode/corber#634]
Application Error
`net:ERR_CLEARTEXT_NOT_PERMITTED`

**Comment by YoranBrondsema** [comment]
I had the same. I followed the instructions from [StackOverflow](https://stackoverflow.com/a/54752717/1269194) and it worked (the file to edit is `corber/cordova/config.xml`).

**Comment by devotox** [comment]
@YoranBrondsema it's funny that didn't work for me. I had to do below

```
config.xml
...
        <resource-file src="network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml"/>
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:networkSecurityConfig="@xml/network_security_config"/>
        </edit-config>
...
```

```
network_security_config.xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
	<base-config cleartextTrafficPermitted="true">
		<trust-anchors>
			<certificates src="system" />
			<certificates src="user" />
		</trust-anchors>
	</base-config>
</network-security-config>
```


Also, this should be automatically done by corber right?

**Comment by YoranBrondsema** [comment]
I imagine this is something that (c|sh)ould be added to corber. Let's see what the maintainers say!

**Comment by alexblom** [comment]
Thanks for reporting this. It should be fixed in todays build.

On android serve/start we are now adding those tags by default - and removing them when you exit serve :)
