### ISSUE TITLE
Is Corber being actively mantained?

### ISSUE THREAD

**Issue by rodrigoyoshida** [isleofcode/corber#637]
I came across Corber a few months ago and found it very useful for projects that need an app but for some reason they do not have the time, team or money to spend creating a new app. Recently I was invited to make a presentation and decided to show Corber there. I really liked this tool but I am afraid it will not be actively mantained in the future. I have been using the `--unsafe-perm` to install Corber on new machines because Phantom is deprecated, this is a known bug since last February. Is Corber actively mantained or it is going to be deprecated in the near future?

**Comment by runspired** [comment]
Yes, although getting off of phantom would be good to do asap :)

**Comment by alexblom** [comment]
Thanks! Yes it is. We are working on more maintenance than feature releases as of late - mostly because the toolset we wanted is stable for our own uses.

Phantom has been presenting a lot of issues, we have been working on a migration path but may have to pull the plug sooner than I would like.

**Comment by rodrigoyoshida** [comment]
Great! I am happy to see Corber is alive, I will be presenting Corber tomorrow on an event called São Paulo Tech Week. It is an event that occurs simultaneously in many places in São Paulo, all of them about technology. Hope I can also contribuite to this project with PRs in the future.

**Comment by alexblom** [comment]
Good luck :)
