### ISSUE TITLE
cordova-ios v5 support?

### ISSUE THREAD

**Issue by tommymetz** [isleofcode/corber#639]
What's the status of support for cordova-ios v5.0? When I run `corber platform add ios` it installs 4.5.5 and when I try and choose the version with `corber platform add ios@5.0.0` it says "'ios@5.0.0' is not a supported platform". Any thoughts?

**Comment by alexblom** [comment]
This should be fixed as of todays release (1.4.2). Tested with 5.1.0

**Comment by tommymetz** [comment]
@alexblom awesome will try it out thanks so much!

**Comment by tommymetz** [comment]
@alexblom hmm, when running `corber platform add ios` it still installs 4.5.5. I've also tried changing in it package.json and config.xml with no luck. Is there a special way to specify 5.1.0 when adding the platform? `corber platform add ios@5.0.0` says it's not a supported platform.

**Comment by alexblom** [comment]
Do you mind posting me the contents of `corber version`?

**Comment by tommymetz** [comment]
@alexblom ahh, didn't realize it was using global corber. 5.1.0 works now. Thanks!

corber (global): 1.3.11
corber (package.json): ^1.4.2
corber (node_modules): 1.4.2
node: 12.13.1
