### ISSUE TITLE
ios release build: failed integrity metadata check

### ISSUE THREAD

**Issue by caltabid** [isleofcode/corber#659]
Hi, when I build an ios release: "corber build --platform=ios --environment=production --release" and run the app on a device, I get a white screen with "failed integrity metadata check" errors on vendor.js and appName.js.
I also replicated the problem with a clean installation (from ember 3.17, added corber, added ios platform, adjusted config files and build).
I found out this is a known issue: https://github.com/jonathanKingston/ember-cli-sri/issues/33#issuecomment-378448379
The proposed workaround just disable "sub resource integrity".
Since this check is working on web and Android I assume it is a corber ios platform issue?
Can anyone help?

**Comment by conormag** [comment]
I think the best solution is follow the resolution and disable sri. Why would you need it anyway when the files are being bundled in signed app and served from the device? 

I don't think this is a corber issue given that its just a thin wrapper around cordova.

**Comment by alexblom** [comment]
This is the correct solution - unfortunately ember-cli-sri does not work with hybrid apps.
