### ISSUE TITLE
Plugin doesn't support this project's cordova version

### ISSUE THREAD

**Issue by maxymczech** [isleofcode/corber#662]
I have updated to latest `corber@1.4.3`. Trying to install `cordova-plugin-firebase-analytics`, I get the following error message:

> Plugin doesn't support this project's cordova version. cordova: 8.0.0, failed version requirement: >=9.0.0

**Comment by alexblom** [comment]
Thank you - this should be fixed in the latest release. You may need to ensure your cordova-lib version is above 9.0. Please re-open if you have any further problems :)
