### ISSUE TITLE
How to run app on android with --proxy that my app could make requests to external API?

### ISSUE THREAD

**Issue by wojtasss** [isleofcode/corber#663]
How to run app on android that my app could make requests to external API?
I need something similar to ```ember s --proxy http://192.168.0.105:3000``` where works perfect.

**Comment by wojtasss** [comment]
Ok I have a workaround for this, I need run 'corber start' only once to deploy app on emulator, then close app and exit from 'corber start' process, and manually start ember s -proxy HERE_MY_PROXY, then open app on android and everything works fine, not sure if this is a bug or what?

**Comment by alexblom** [comment]
We dont support proxies like this at this moment with start. You can use `corber serve` - which will run the server without auto deploying to your platform and should accept the proxy option. Thanks!

**Comment by jking6884** [comment]
@alexblom is there any plan to add support for this on the start command going forward?
