### ISSUE TITLE
Android Setup Variable `ANDROID_HOME ` Needed

### ISSUE THREAD

**Issue by joel** [isleofcode/corber#666]
The Android Setup Page http://corber.io/pages/android-setup mention to set up the variable `ANDROID_SDK_ROOT`

```
Ensure your ANDROID_SDK_ROOT env variable is configured -> Mac/Linux
#~/.bash_profile
export ANDROID_SDK_ROOT=/Users/foo/Library/Android/sdk
```

But it turns out that Gradle use `ANDROID_HOME`

<img width="808" alt="Screen Shot 2020-06-09 at 5 21 08 PM" src="https://user-images.githubusercontent.com/5789/84166841-c0288d00-aa75-11ea-8a23-ca17c5805d92.png">

Otherwise you get 

```
No installed build tools found. Install the Android build tools version " + minBuildToolsVersion + " or higher.
```

Likely 
```
No installed build tools found. Install the Android build tools version 19.1.0 or higher.
```

**Comment by alexblom** [comment]
Thank you - this looks like an upstream update. I have amended the docs!
