### ISSUE TITLE
corber make-icons for android additional with round icons

### ISSUE THREAD

**Issue by Timbuktu1982** [isleofcode/corber#668]
Hi there,

i have following problem:
When i generate the app-icons with make-icons, i will get a set of icons. But in android phones with round icons i see no full icon, the icons are centered and zoomed out. When i use android studio to generate the icons, i can create legacy and adaptive icons and they will be includes round icons, so i have no problem on the phones with round icons. The icons will be displayed in full.

Gives a option to generate a full set of icons with make-icons?

Thank you

**Comment by Timbuktu1982** [comment]
No idea??

**Comment by alexblom** [comment]
We will actually be removing the icon sets completely from corber - if you want to extend I'd suggest looking at https://github.com/isleofcode/splicon directly. Cheers!
