### ISSUE TITLE
ionic 5 run on android using vs code

### ISSUE THREAD

**Issue by sankar3003** [isleofcode/corber#671]
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\Users\SPCP285\AppData\Local\Android\Sdk (recommended setting)
ANDROID_HOME=C:\Users\SPCP285\AppData\Local\Android\Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\SPCP285\ionicmini\platforms\android\CordovaLib\build.gradle' line: 48

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Plugin with id 'com.github.dcendents.android-maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
> Configure project :CordovaLib
C:\Users\SPCP285\ionicmini\platforms\android\gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\SPCP285\ionicmini\platforms\android\CordovaLib\build.gradle' line: 48

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Plugin with id 'com.github.dcendents.android-maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android --device exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

and my requirements are

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\SPCP285\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 6 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\SPCP285\AppData\Local\Android\Sdk)
   NodeJS            : v14.4.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 10

**Comment by alexblom** [comment]
I think your issue is maven vs corber related - unfortunately these snags will just happen some times. I think you will find this link helpful - if not let me know! https://stackoverflow.com/questions/28871084/how-to-fix-plugin-with-id-com-github-dcendents-android-maven-not-found-in-and
