### ISSUE TITLE
Package version should update from package.json

### ISSUE THREAD

**Issue by optikalefx** [isleofcode/corber#93]
Right now I have to increment the version in both config.xml and package.json. Maybe this is desirable by some, but probably not. config.xml should probably read from package.json

**Comment by alexblom** [comment]
Agreed. I have a very WIP branch that removes most direct usage of config.xml, in favour of placing it in ember-cordova. On top of versions, you can set variables based on ENV similar to how config/environment.js works in Ember.

**Comment by jviney** [comment]
I've done something similar. The parts of config.xml that differ between environments are kept in config/environment.js. A beforeBuild ember-cordova hook rewrites config.xml appropriately for the current EMBER_ENV value.

**Comment by jelhan** [comment]
An ember-release hook would be another approach. Since ember-release is commonly used to create a git tag and update package.json it would make sense if it also updates config.xml.

**Comment by alexblom** [comment]
I'm going to close this issue due to the broader conversation of rewriting configs in general - which will inevitably support this.
